language: java
jdk:
  - openjdk8

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - joerg.hohwiller@googlemail.com
